- name: Create undercloud configuration
  template:
    src: "{{ undercloud_config_file }}"
    dest: "./undercloud.conf"
    mode: 0600

- name: Create undercloud pre-install script
  template:
    src: "{{ undercloud_pre_install_script }}"
    dest: "{{ working_dir }}/undercloud-pre-install.sh"
    mode: 0755

- name: Create undercloud install script
  template:
    src: "{{ undercloud_install_script }}"
    dest: "{{ working_dir }}/undercloud-install.sh"
    mode: 0755

- name: Create overcloud image generation script
  template:
    src: "{{ overcloud_images_script }}"
    dest: "{{ working_dir }}/overcloud-images.sh"
    mode: 0755
